### ISSUE TITLE
Helping Hand!

### ISSUE THREAD

**Issue by bevacqua** [nodeschool/buenosaires#1]
Buenas,

Ví el mail en la lista de NodeJS-Argentina y quería colaborar; necesitan más tutores?

**Comment by a0viedo** [comment]
Hola Nico! Toda mano es más que bienvenida. De hecho se anotó mucha más gente de la esperabamos por lo que sí vamos a necesitar todos los tutores que podamos conseguir. Conocías el formato ya de los workshops?

**Comment by bevacqua** [comment]
Dentro de todo si: nunca fui fisicamente pero si use adventure y segui
alguno q otro en mi pc

On Monday, October 13, 2014, Alejandro Oviedo notifications@github.com
wrote:

> Hola Nico! Toda mano es más que bienvenida. De hecho se anotó mucha más
> gente de la esperabamos por lo que sí vamos a necesitar todos los tutores
> que podamos conseguir. Conocías el formato ya de los workshops?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/buenosaires/issues/1#issuecomment-58913619
> .

## 

github https://github.com/bevacqua · blog http://blog.ponyfoo.com/ ·
twitter https://twitter.com/nzgb · book http://bevacqua.io/buildfirst ·
career http://careers.stackoverflow.com/bevacqua ·about
http://bevacqua.io/

**Comment by eafelix** [comment]
Yo igual nico, pero creo q vamos bien, tenemos q coordinar esta semana para juntarnos y charlar el tema con ale.

**Comment by bevacqua** [comment]
Puede ser online? Yo esta semana no puedo, la q viene puedo x internet, y desp tengo campjs.com

Perdon x complicarla!
