### ISSUE TITLE
Tutor git

### ISSUE THREAD

**Issue by diegosanchez** [nodeschool/buenosaires#10]
Si actualmente están necesitando tutores de git me ofrezco para dar una mano

**Comment by a0viedo** [comment]
Buenas diego! Perfecto, y con el resto de los workshoppers cómo te ves? Algo de javascript sabés?

**Comment by diegosanchez** [comment]
**La respuesta corta**: Bien, me veo bien.

**La respuesta larga**
En el día a día trabajo con otras tecnologías pero JS lo utilizo en proyectos personales.  Como actualmente estoy aprendiendo NodeJS comencé a estudiar JS (del lado del servidor); es por esto que a continuación te comento el nivel en el que estoy (el comentario busca preservar la calidad del workshop en lugar de hacer _autobombo_, je!)

_Mis conocimientos respecto a JS_:
- Closures 
- Prototype chain
- Hoisting
- Function scoped variables
- String, array usage (pero debo leer la documentación a modo de referencia)

_Mis conocimientos respecto a NodeJS_:
- Instalación node
- Estructura package.json
- Módulos: fs, path, http, stream, connect
- Pipes
- npm
  (conocimientos recientes)

Si queres podríamos hacer un Hangout/Skype para hablar y que lo consideres

**Comment by a0viedo** [comment]
yo diría que estás en condiciones de tutorear [javascripting](https://github.com/sethvincent/javascripting) también. fijate si en algun momento te haces un tiempo para hacer esos ejercicios (no debería llevarte más de 15/20 min) y comentame si te pareció muy fácil, si tenés alguna sugerencia también, si le cambiarías algo, etc

**Comment by eafelix** [comment]
Recuerden que esta incompleto el workshop de https://github.com/sethvincent/javascripting , después tenemos que discutir cual deberíamos agregar de los faltantes puntos propuestos. Después levanto un issue

**Comment by a0viedo** [comment]
@eafelix si, lo sé...tengo pensado agregar al menos estos trés ejercicios para esta semana:
- "ACCESSING ARRAY VALUES"
- "OBJECT KEYS"
- "FUNCTION ARGUMENTS"

que una vez con esos creo que estaría bastante completo. elegí dejar _this_ y _scope_ afuera porque pienso que son los que tienen mayor complejidad

**Comment by diegosanchez** [comment]
@a0viedo realicé los ejercicios que se propusieron para el workshop ([LearnYouNode](https://github.com/a0viedo/learnyounode), [stream-adventure](https://github.com/eafelix/stream-adventure), [Javascripting](https://github.com/eafelix/javascripting)). Muy buenos todos.

Inspeccionando las soluciones propuestas ví que hay conceptos de JS que se utilizan y que se pueden incorporar en el WS de [Javascripting](https://github.com/eafelix/javascripting). Temas:
1.- Funciones anónimas
2.- Operador condicional "_( condición )? (true) : (false)_"
3.- Scope, Hoisting (se utiliza aquí [duplexer_redux](https://github.com/eafelix/stream-adventure/blob/master/problems/duplexer_redux/solution.js#L9)).
4.- Expresiones regulares (se utiliza aquí [http_json_api_server](https://github.com/a0viedo/learnyounode/blob/master/exercises/http_json_api_server/solution/solution.js#L21)).

Los dos primeros puntos son sencillos. El tercero es un poco más difícil de ver , y esta relacionado con _scopes_. La última se podría obviar, tranquilamente.

Respecto a la dificultad del WS: En principio creo que es sencillo. Ahora, ¿es conveniente sumarle dificultad? Bueno, dependerá de quienes van a asister. Yo sumaría estos dos temas:
- Closures
- Scopes

Cuando comencé con JS, habiendo trabajado con (C++/Smalltalk), lo más complejo fue entender Scopes & Closures. Tal vez esto esté más allá del scope de WS, pero creo resultaría útil cubrirlo para aquellos que comienzan. Sino, quedará para la próxima.

**Comment by a0viedo** [comment]
Es un tema que dá para charla. Desde mi punto de vista, creo que javascripting es uno de los pocos workshoppers que no requieren conocimientos previos y está al alcance de todos. Agregarle temas complejos (closures en particular) sería contraproducente. 

Lo que sí estoy de acuerdo es agregar otros niveles, tal vez javascripting2? Por ejemplo todavía pienso que para alguien al que le cueste los ejercicios de learnyounode, stream-adventure sería cómo darse con una pared. Falta un poco más de contexto o una explicación más detallada en cada ejercicio.
