### ISSUE TITLE
Encuesta Sábado 15 de Noviembre

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/buenosaires#11]
Hola!

Gracias a todos por participar del evento. Quisiera utilizar este espacio para recolectar comentarios, opiniones, experiencias, críticas constructivas, todo sirve.

Las preguntas que les quisiera hacer a los participantes son:
1. ¿la pasaste bien?
2. ¿aprendiste algo? ¿pudiste resolver las dudas que te surgieron? 
3. ¿cambiarías/agregarías algo? Cualquier recomendación es bienvenida :smiley: 
4. ¿cada cuanto tiempo te gustaría tener un evento NodeSchool?

**Comment by nicolasmartinrojo** [comment]
1. ¿la pasaste bien?, muy.
2. ¿aprendiste algo? ¿pudiste resolver las dudas que te surgieron? . aprendí bastante de node. me sirvió mucho y pude despejar todas las preguntas
3. ¿cambiarías/agregarías algo? Cualquier recomendación es bienvenida :smiley:no, la organización y la atención fueron muy buenas
4. ¿cada cuanto tiempo te gustaría tener un evento NodeSchool?. 1 x mes!

**Comment by durancristhian** [comment]
1. ¿la pasaste bien? 
   la pasé excelente
2. ¿Aprendiste algo? ¿Pudiste resolver las dudas que te surgieron? 
   sí, aprendí muchísimo, y las dudas que fueron surgiendo las charlaba con alguno que tuviera cerca, por suerte la mayoría estaba con el mismo ejercicio
3. ¿Cambiarías / agregarías algo?
   Mas stickers :+1: :smile: 
   No, en serio, No se si cambiaría algo, fué muy buena la predispocisión de los muchachos que estaban dando vueltas para preguntarles cosas.
4. ¿Cada cuanto tiempo te gustaría tener un evento NodeSchool?
   1 por mes como cualquier meetup yo creo que sería suficiente

**Comment by sbaglieri** [comment]
1. Excelente.
2. Si, habia muy buena predispocisión a resolver dudas que iban surgiendo.
3. Quizas la organización de los grupos, como que nadie sabia donde ir y podias terminar en una mesa con el nivel muy desparejo. Lo cual puede llegar a inhibir a los mas novatos y aburrir a los que estan mas curtidos.
4. Una vez por mes seria genial.

**Comment by emaxi** [comment]
1. Genial
2. Totalmente
3. Pair programming de a dos por mismo nivel no estaría mal probar si funciona. Quiza solo hay que probarlo.
4. Cada un mes me parece bien

**Comment by hnovillo** [comment]
1. ¿la pasaste bien?
   Lo pase de diez! che! Muy buena onda! Y lo solidario que han sido de todos, gente de AreaTres, los asistentes que nos ayudaron con los ejercicios, y también la buena onda de todos....... especialmente  en mi caso que caí sin compu y Nico Isnardi, muy amablemente me prestó la suya....
2. ¿aprendiste algo? ¿pudiste resolver las dudas que te surgieron? 
   por supuesto que aprendí... sobre todo el tema de los callbacks! Es otra forma de pensar para los que venimos de la programación web tradicional. 
3. ¿cambiarías/agregarías algo? Cualquier recomendación es bienvenida  
   Quizás estaría bueno hacer los ejercicios en grupo de dos o tres personas para no tener que dedicarle tanto tiempo en algunas cuestiones... pero no es algo que sea tan imprescindible....
4. ¿cada cuanto tiempo te gustaría tener un evento NodeSchool?
   Cada un mes/mes y medio... para que la bruja no se retobe... =0P

**Comment by diegosanchez** [comment]
1. ¿la pasaste bien?
   Si, muy buena onda todos (los alumnos y tutores)
2. ¿aprendiste algo? ¿pudiste resolver las dudas que te surgieron?
   Si.
3. ¿cambiarías/agregarías algo? Cualquier recomendación es bienvenida 
   3.1 :+1: a Pair programming
   3.2 :+1: a agrupar a los participantes en grupos según skills.
   3.3 Agregar ejercicios pácticos donde se puedan aplicar los conceptos aprendidos.
   3.4 Discutir/analizar códigos de módulos (por ejemplo [through](https://www.npmjs.org/package/through)).
   3.5 Solucionar un problema del día a día utilizando NodeJS (tarea para el hogar). Luego discutir distintos approaches en la reunión.
4. ¿cada cuanto tiempo te gustaría tener un evento NodeSchool?
   1xMes es razonable.  Pero dependerá de las actividades que se planteen para la reunión.
