### ISSUE TITLE
International Day Date

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/buenosaires#17]
Can you please update your preferred date in the international ns day enrolment form.  I should have been more explicit and asked for dates in may.

I have since updated the form: http://goo.gl/forms/OUAysPGJ9q

Apologies for the inconvenience

**Comment by eafelix** [comment]
thanks! we do it soon.
@a0viedo we need decide this.

**Comment by a0viedo** [comment]
closing this, but we can't wait till next year!
