### ISSUE TITLE
Traducción Learnyounode 

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/buenosaires#2]
@theHazzard es el que estuvo haciendo todas las traducciones. Estábamos utilizando mails para organizarnos, creo que si seguimos por acá podemos mejorar la visibilidad para con el resto de los tutores. El repo es un [fork](https://github.com/a0viedo/learnyounode) del original e idealmente quisieramos crear un pull request para incorporar los cambios en el workshop oficial. 

Update: @pdjota tiene un [fork](https://github.com/pdjota/learnyounode/tree/translation-es) ya traducido.

**Comment by julianduque** [comment]
Excelente, desde nodeschool/medellin podemos unir esfuerzos, nos interesa mucho

**Comment by a0viedo** [comment]
@julianduque justamente estábamos pensando en contactarlos a uds, Costa Rica y Puerto Rico también. (@gaboesquivel @gcollazo)

**Comment by julianduque** [comment]
@edsadr tambien ha trabajado en el tema

**Comment by theHazzard** [comment]
hola! yo estuve haciendo las traducciones de los primeros 5 ejercicios, si
ven algo que se podría corregir avísenme! seria genial que pudiéramos
trabajar todos juntos en esto =)

Por lo de unir al repo original lo veo medio complicado, ya que
learnyounode utiliza archivos .md (markdown) para describir los ejercicios,
lo que yo estuve haciendo fue cambiar el texto de estos ejercicios.

Saludos!

[H]azzard.-
thehazzard@gmail.com

2014-10-13 13:29 GMT-03:00 Julian Duque notifications@github.com:

**Comment by a0viedo** [comment]
@theHazzard creo que ya está pensado cómo hacerlo, una vez que terminemos la traducción actualizamos el estado en el [issue](https://github.com/rvagg/learnyounode/issues/126).

**Comment by theHazzard** [comment]
Buenísimo, hay mas gente para las traducciones? yo estoy terminando el ejercicio 6.

**Comment by a0viedo** [comment]
mañana voy a hablar con @nisnardi, se ofreció a darnos una mano también.
por otro lado, si empiezan la traducción de un ejercicio por favor avisenlo acá, de esa forma no nos pisamos

**Comment by eafelix** [comment]
Ahora hago el fork del workshop faltante.
genial la mano chicos!!!

**Comment by nisnardi** [comment]
Hola, yo me sumo. Ale mañana hablamos bien y coordinamos!

Abrazo

**Comment by theHazzard** [comment]
Ya esta finalizado el ejercicio 6, a partir de ahora para cada ejercicio que inicie abriré un issue, disculpen las molestias!

**Comment by julianduque** [comment]
La idea es tener el contenido antes de darle soporte en workshopper, ya hay algunas propuestas pero no hay contenido full traducido.

**Comment by pdjota** [comment]
Estimados:
Nosotros hemos traducido el learnyounode,
https://github.com/pdjota/learnyounode/tree/translation-es
Nos faltaría traducir el workshopper, @julianduque conviene traducir directamente el workshopper o mejor ponerle algún tipo de i18n?
Saludos,
Pablo

**Comment by a0viedo** [comment]
@pdjota excelentes noticias! podemos seguir directamente con streams-adventure entonces

**Comment by theHazzard** [comment]
jaja un bajón para mi que venia traduciendo como un campeón (? si hay algo
para traducir de streams adventure tírenme un hueso

[H]azzard.-
thehazzard@gmail.com

2014-10-14 9:21 GMT-03:00 Alejandro Oviedo notifications@github.com:

**Comment by gcollazo** [comment]
¿Llego tarde? ¿Queda algo por traducir?

cc: @khalifenizar @jpadilla @froi @elving

**Comment by eafelix** [comment]
En el readme del repo estan los links a los forks que acumulan las traducciones, 
Ale estaba mirando de que forma llevarlos al master con los admin.  
Ya el de learnyounode lo modifico para que apunte al de @pdjota  

Gracias, va de 10 todo!

**Comment by a0viedo** [comment]
gracias a la ayuda de @pdjota la traducción ya está completa. seguimos con la traducción de javascripting #5
