### ISSUE TITLE
Hola gente. Me copa mucho la idea. Cómo es el tema de la mentoría?

### ISSUE THREAD

**Issue by santiagobasulto** [nodeschool/buenosaires#22]

**Comment by eafelix** [comment]
Genial por la iniciativa!!
Sumate al chat, presentate y te comentamos por ahi. 
Para darte un paneo rapido, mas que nada consiste en saber bien los core workshops.
Los estuviste mirando?

**Comment by a0viedo** [comment]
Buenas @santiagobasulto, contanos acerca de vos! Qué hacés, por qué te interesa y cual son tus expectativas.

**Comment by a0viedo** [comment]
Cierro esto por falta de respuesta :(
