### ISSUE TITLE
agregarse en el código de conducta

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/buenosaires#28]
Agregarse los tutores que todavía no están en [codigodeconducta.md](https://github.com/nodeschool/buenosaires/blob/gh-pages/codigodeconducta.md)
/cc @diegosanchez @jaclar @nescalante @mgtitimoli

**Comment by diegosanchez** [comment]
Ok me agrego siguiendo orden alfabético

**Comment by a0viedo** [comment]
Que conste que se los dije.
