### ISSUE TITLE
Registración para NodeSchool

### ISSUE THREAD

**Issue by jmr85** [nodeschool/buenosaires#29]
En <a href="https://ti.to/nodeschool/buenosaires-marzo-2015">NodeSchool Buenos Aires</a> dice: "La registración no se encuentra disponible". ¿No hay mas lugar?

**Comment by a0viedo** [comment]
@jmr85  se acabaron los lugares rápido! estamos viendo con el sponsor de abrir 10 lugares más

**Comment by jmr85** [comment]
@a0viedo Ok, gracias de todas maneras
