### ISSUE TITLE
Traducción streams-adventure

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/buenosaires#3]
El repo es un [fork](https://github.com/eafelix/stream-adventure) del original, al igual que con learyounode, quisieramos luego crear un pull request y que se incorpore al original de alguna forma.

**Comment by eafelix** [comment]
Yo esta semana comienzo con los primeros 5 puntos, de terminar y no haber otros puntos asignados, continuo.

**Comment by diegosanchez** [comment]
Me gustaría poder colaborar. Cuáles serían las prioridades?

**Comment by a0viedo** [comment]
la traducción ya está finalizada: https://github.com/eafelix/stream-adventure
