### ISSUE TITLE
Imágen de fondo en landing pesa 3.2 MB

### ISSUE THREAD

**Issue by bevacqua** [nodeschool/buenosaires#36]
![screen shot 2015-05-05 at 15 52 16](https://cloud.githubusercontent.com/assets/934293/7480381/95f2ffc8-f33e-11e4-939f-178c8796df4f.png)

**Comment by eafelix** [comment]
Si jajajajajajaj, lo vimos con ale y nunca lo cambiamos. Perdón por la bestialidad, los tiempos apremiaban.
