### ISSUE TITLE
Workshopper javascripting

### ISSUE THREAD

**Issue by a0viedo** [nodeschool/buenosaires#5]
Dado que es un nivel de participantes con cero experiencia [considerable](http://imageshack.com/a/img540/4115/HP2o1T.png), quisiera proponer el workshopper [javascripting](https://github.com/sethvincent/javascripting) para aquellos que no tengan experiencia. Si bien hay ejercicios en CodeAcademy traducidos al español, no me hablaron muy bien acerca de cómo funcionan. Ideas?

**Comment by eafelix** [comment]
Mira, los chicos subieron un workshop de javascript
podriamos chusmetearlo https://github.com/sethvincent/javascripting

**Comment by theHazzard** [comment]
Me sumo a la traduccion!

**Comment by a0viedo** [comment]
no es prudente comenzar con la traducción hasta que se termine de agregar los ejercicios fundamentales en el workshopper. una vez hecho eso seguimos con la traducción

**Comment by theHazzard** [comment]
Si necesitan ayuda peguen el grito

**Comment by a0viedo** [comment]
@theHazzard te animás a hacer un ejercicio? "ACCESSING ARRAY VALUES" por ejemplo

**Comment by a0viedo** [comment]
Ok empecé con la traducción y unas mejoras en el branch [es](https://github.com/a0viedo/javascripting/tree/es) por si alguno quiere aportar.
cc @nodeschool/buenosaires

**Comment by diegosanchez** [comment]
Como puedo colaborar? Traduzco los solution.md?

**Comment by a0viedo** [comment]
La idea es traducir en bloques de ejercicios. Por cada ejercicio, traducimos **problem.md**, **solution.md** y si hace falta el chequeo de la solución en **index.js** también.

**Comment by diegosanchez** [comment]
Ok, cual es la manera de sincronizarse? Crearíamos un issue en el proyecto?

**Comment by a0viedo** [comment]
La idea es crear un pull request por ejercicio al [repo](https://github.com/a0viedo/javascripting). Acuerdensen que las traducciones van al branch [es](https://github.com/a0viedo/javascripting/tree/es).

**Comment by a0viedo** [comment]
translation done:https://github.com/a0viedo/javascripting

@khalifenizar commited to add i18n to **workshopper** here: https://github.com/nodeschool/organizers/issues/64

**Comment by nizaroni** [comment]
Con calma, con calma. Espero encontrar tiempo para trabajarlo este fin de semana. :smile:

Mi idea inicialmente será integrar varias carpetas de ejercicios en el mismo repo de cada taller para que no haya que hacer un fork para las traducciones. Luego añadiré la capacidad de usar language files para no tener que duplicar el código que no cambia entre idiomas (por ejemplo el código de verificar la solución).

¿Qué otro problema han encontrado al traducir talleres?
