### ISSUE TITLE
Call entre Tutores y Coordinadores 

### ISSUE THREAD

**Issue by eafelix** [nodeschool/buenosaires#9]
Chicos , esta semana hacemos la call para coordinar algunos aspectos del workshop ?

**Comment by bevacqua** [comment]
:+1:

**Comment by a0viedo** [comment]
+1. qué día y horario les conviene?
@jaclar @nescalante

**Comment by nescalante** [comment]
mañana? jueves?

**Comment by a0viedo** [comment]
@theHazzard si podés, también estaría bueno que te sumes a compartir ideas

**Comment by theHazzard** [comment]
por supuesto =), siempre y cuando no este trabajando =(

**Comment by a0viedo** [comment]
confirmamos mañana martes 12:00hs GMT -3

**Comment by eafelix** [comment]
confirmado!

**Comment by jaclar** [comment]
confirmado. como hacemos el call?

**Comment by a0viedo** [comment]
hangouts?

**Comment by bevacqua** [comment]
dale

github https://github.com/bevacqua · blog http://blog.ponyfoo.com/ ·
twitter https://twitter.com/nzgb · book http://bevacqua.io/buildfirst ·
career http://careers.stackoverflow.com/bevacqua ·about
http://bevacqua.io/

On Tue, Oct 21, 2014 at 10:05 AM, Alejandro Oviedo <notifications@github.com

**Comment by a0viedo** [comment]
Paso a dejar el resúmen de la call:
- Avisar con tiempo para que los participantes instalen Node antes de asistir al evento.
- Al momento de iniciar el evento, dar una pequeña introducción de Nodeschool y la comunidad que lo impulsa. También explicar pasos a seguir para completar un ejercicio simple.
- Tener pendrives preparados con los instalables de Node (Linux, Windows y OSX) y los workshops en formato tar, de forma que podamos realizar el evento sin conexión a internet
- Cada tutor debería poder tutorear los workshoppers que son parte del core (o al menos en su mayoría).
- Cada tutor también puede championar workshops, es decir preparar workshops opcionales para tutorear.
- [¿Qué beneficios trae tener un team en nodeschool?](https://github.com/nodeschool/organizers#3) Básicamente dice para que puedan abrir y cerrar issues, así también cómo pushear código. A mi parecer creo que lo de pushear código no sería lo más recomendable. 
- La idea es que esté al alcance de alguien que no tiene experiencia en programación. Pero lo mínimo indispensable es: ¿uso de la terminal? ¿qué más?
- Algunos workshops requieren compilar binarios, lo cual requiere Visual Studio en Windows y XCode en OSX. @jaclar propuso un pendrive booteable con Ubuntu y Node ya instalado. ¿Alguna otra sugerencia?

¿Me olvidé de algo?

Y tengan en cuenta qué, en el transcurso de todo eso, lo ideal (si no es lo principal) sería que tanto los participantes cómo los tutores se diviertan.

**Comment by bevacqua** [comment]
Excelente recap, después podemos pasarselo a los q no pudieron estar en la call

**Comment by eafelix** [comment]
Genial!
